<?php

namespace app\controllers;

use app\models\MailForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;


class   CommonController extends Controller
{
    public $layout='index';
    public function init()
    {
        $userInfo =Yii::$app->session->get(Yii::$app->params['redisUserinfoKey']);
        Yii::$app->view->params['userInfo']=json_decode($userInfo,true);
        $seo['title'] ='jQuery插件库-收集最全最新最好的jQuery插件';
        $seo['keywords'] ='jQuery,jQuery特效,jQuery ui,jQuery插件,jQuery 教程,css3,网页特效,JS特效';
        $seo['description'] ='本站致力于收集jQuery插件和提供各种jQuery特效的详细使用方法,在线预览，jQuery插件下载及教程';
        Yii::$app->view->params['seo']=$seo;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     *  404页面
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


}
