<?php

namespace app\controllers;

use app\models\WebSource;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SubmitController extends Controller
{
    public $layout='submit';

    public function init()
    {
        $userInfo =Yii::$app->session->get(Yii::$app->params['redisUserinfoKey']);
        Yii::$app->view->params['userInfo']=json_decode($userInfo,true);
        $seo['title'] ='jQuery插件库-收集最全最新最好的jQuery插件';
        $seo['keywords'] ='jQuery,jQuery特效,jQuery ui,jQuery插件,jQuery 教程,css3,网页特效,JS特效';
        $seo['description'] ='本站致力于收集jQuery插件和提供各种jQuery特效的详细使用方法,在线预览，jQuery插件下载及教程';
        Yii::$app->view->params['seo']=$seo;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionWeb()
    {
        $model = new WebSource();
        if(Yii::$app->request->isPost) {
            $model->resources= UploadedFile::getInstanceByName('resources');
            $model->load(Yii::$app->request->post(), '');
            $checkRes = $model->validate();
            if (!$checkRes) {
                return $this->render('web', [
                    'error' => reset($model->getErrors())[0],
                    'model' => $model
                ]);
            }

            if(!$model->upload()){
                return $this->render('web', [
                    'error' =>'文件上传失败',
                    'model' => $model
                ]);
            }
            $result = $model->addWebSource();
            if(!$result){
                return $this->render('web', [
                    'error' =>'发布失败',
                    'model' => $model
                ]);
            }
        }
        return $this->render('web',['model'=>$model]);
    }



}
